language: java
deploy:
  provider: cloudfoundry
  username: chris.ko791@gmail.com
  password: 
    secure: fH8A/OaLYjJ5tXw4NEXdkY0XSZ3QPcDqvolwJQiIOx00vJRZ8mCnx3Ev19y65S5Rli5fSsMnQTZCrrlZus0+3PPf+AatFKjjvvrw6XYvGNh4MY9bRai/PNfLNDShryntHGVhnPFJlYs/xBcaTfzR/SsXdMNtIR5Ui4cFNI7QxYvKYX3K3VZaInQeneUd5Qg3HfB/b8vW/AoUubWJiuEWGERppLyQ3ZNIdBOiE3J2sKaOe/oSSj/Z2VBwFpeOVYcYABOFSSVESb+fkHkLoHYhJDwM823Djkjo4cWyanE5t5WcRKgDq7ILO+LXrgcLnyprP3avcAVH5Q36oER/OX35c2k3JFnPtSjqkFOum2VpDyRKrgbfYdIMVR9OvXxd3Nnz/ORc+C+9KIlsgl3xSDttW6fYilCIkKAJfQ9+EEUSZpwtlCdWYyl6uh0ApqBI17Hw0Ta5fJ9gQddhMveIIilG2essVy4eLFiiUe24qCRp9TDb9fu6C5HsFnxVdr/Bzva+TTA18QVzCJkP3F4oVUtod4xNHq0y0stUvJG0SfvW/N4q0sUqMP98kcaKrexgXdHoo/Vb5kHllpcdP8WhF3sWktZN50QwAkd2oUnEyiY5bpBtiv+Tix3K2mPgbPBDCOIBLc5GJgNSoLEH+4JtvEUiHAbqqKSBXjtoAZjkumMLRbk=
  api: https://api.run.pivotal.io
  organization: dataflow-test
  space: development

